name: Run Postman Tests with Newman

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  newman_test:
    runs-on: ubuntu-latest

    steps:
      # Lấy mã nguồn của kho lưu trữ
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # Chọn phiên bản Node.js bạn muốn

      # Cài đặt Newman và các dependencies
      - name: Install dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      # Chạy kiểm thử Postman với Newman
      - name: Run Newman tests
        run: |
          newman run User_Test.json -e ShoesStoreEnv.json --reporters html --reporter-html-export report.html --verbose

      # Upload báo cáo HTML dưới dạng artifact
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: report.html
